app1/urls.py
from app1.views import *
from django.urls import path
app_name='anything'

urlpatterns=[
    path('ganesh',ganesh,name='ganesh')
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='something'

urlpatterns=[
    path('ragnar/',ragnar,name='ragnar')
]

specific_url_navigation/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def ganesh(request):
    return render(request,'ganesh.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def ragnar(request):
    return render(request,'ragnar.html')

templates/ganesh.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>specific Url Navigation</h1>
        <h1>whats your Name</h1>
        <a href="{% url 'something:ragnar' %}">response from ragnar</a>
    </center>

</body>
</html>

templates/ragnar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>response</h1>
        <h1>King Ragnar That is my name</h1>
        <a href="{% url 'anything:ganesh' %}">responses</a>
    </center>
</body>
</html>